import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "../styles/globals.css";
import { ReactNode } from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const jost = Jost({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={jost.className} style={{ height: "100%" }}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
